import { addRouterPrefixFun } from "./toolUtil"
export const lian_path = addRouterPrefixFun('/lian')
export const login_path = addRouterPrefixFun('/login')
export const home_path = addRouterPrefixFun('/')
export const nft_path = addRouterPrefixFun('/nft')
export const nft_addSeries_path = addRouterPrefixFun('/nft/addSeries')
export const nft_add_path = addRouterPrefixFun('/nft/add')
export const nft_list_path = addRouterPrefixFun('/nft/list')
export const nft_detail_path = addRouterPrefixFun('/nft/detail')
export const nft_coins_path = addRouterPrefixFun('/nft/coins')
export const user_path = addRouterPrefixFun('/user')
export const user_wallet_path = addRouterPrefixFun('/user/wallet')
export const pool_path = addRouterPrefixFun('/pool')
export const log_path = addRouterPrefixFun('/log')
export const integral_path = addRouterPrefixFun('/integral')
